### ISSUE TITLE
How about DIY SmartDNS Proxy in addition to smartVPN?

### ISSUE THREAD

**Issue by siliconhippy** [mrahmadt/SmartGW#1]
Great work !

Now can you build/add a DIY SmartDNS Proxy in addition to the smartVPN with a Linux server/ OpenWrt router?

The main problem with VPNs is encryption kills speed in many cases, and what if you only want geo unlocking or other proxy services by setting up your own server to eliminate 3rd party payments/snooping ?

**Comment by mrahmadt** [comment]
Hi

You can use SmartGW as a SmartDNS, you will need to install it on a server in the region you are interested in and ignore the <a href="https://github.com/jotyGill/openpyn-nordvpn">openpyn-nordvpn</a> installation part, then change the DNS of your router to the IP of your server (make sure to setup your server firewall to accept only requests from your router IP).

Or you can use <a href="https://github.com/oblique/proxflix">oblique/proxflix</a>.

**Comment by siliconhippy** [comment]
Good ! I like the container idea too...

1. Re: "region you are interested in", you really mean where I would like to watch TV streaming, not the regions it originates from e.g. Netflix US, BBC iPlayer UK etc.

2. This should do multiple geo unlocks at the same time, like SmartDNS Proxy servers are supposed to?

3. Does traffic pass through the SmartDNS Proxy server, or somehow bypass it (meaning the proxy server has very light load)?

4. Will the Docker oblique/proxflix work with the https://Pi-hole.net Debian Docker to run on LibreElec or will there be conflicts?

As you know, Pi-hole does DNS blocks but also has DNS/DHCP server config GUI with the usual upstream DNS servers from router IP DNS redirect.

So I could simply point Custom DNS in Pi-hole upstream entry to this DIY SmartDNS Proxy server IP?

**Comment by mrahmadt** [comment]
1- you need your server to be in the same region of the TV. Example to watch BBC iPlayer UK your server must be in UK

2- this will do geo unlock for it own region only , you need to setup a server for each region 

3- pass through the smartdns server 

4- I assume yes but check with proxflix

What are you trying to achieve from this setup? If you want geo unlock for multiple regions I think it’s better to subscribe with a ready smartdns service
