### ISSUE TITLE
Info about program and future implementation

### ISSUE THREAD

**Issue by Jorman** [mrahmadt/SmartGW#3]
Hi, I just see this project, jotyGill from openpyn-nordvpn inform me about this.

I've only some question.

1. Do you know if this works with modified firmware? Like DDWRT or Voxel firmware for Netgear.
2. Do you plan to filter even for lan mask? Let's see I want that all traffic from 192.168.0.15 and 192.168.0.22 are with vpn.

Many thanks and have a nice day

**Comment by mrahmadt** [comment]
A new version has been released, this release is based on containers so it should work any device that supports containers.
