### ISSUE TITLE
Domains are not stored

### ISSUE THREAD

**Issue by davidohne** [mrahmadt/SmartGW#4]
Hey!
Don't know if it is on my side or if it is a normal behaviour because of docker, but all my domains are not stored so I would have to add them every time the server restarts or the docker service is reloaded. Is there any way to store the domains?

Thanks for your great app!

**Comment by mrahmadt** [comment]
Apologize for the late response, seems I'm not getting any notification from GitHub

It should store your domains without any issue, check the permission of docker volume

`docker volume inspect smartgw_etcdnsmasqd`

Also with the new pihole update you can use "Local DNS Records" to store your domains and point it to the IP address of your smartgw_sniproxyvpn container
